{
 "title": "NginxaaS Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vm",
    "label": "Virtual Machine",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "NGINXaaS - ${var.project_prefix}",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "NCU Stats",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName": "ncu.provisioned",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName": "ncu.requested",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINXaaS Statistics",
      "dimensionFilters": [],
      "metricName": "ncu.consumed",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX connections statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginx极ployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX worker statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.total",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.response.time",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.2xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.3xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.4xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.5xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGIN极.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX connections statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.cpu",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-grafana"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX worker statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.total",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.response.time",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.2xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.3xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.4xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.5xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX system statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.cpu",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.packets_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.packets_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.total_bytes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.egress_throughput",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SSL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.handshakes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.reuses",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.handshakes_timeout",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Cache Statistics",
      "dimensionFilters": [
       { "dimension": "cache_zone", "filters": [ "image_cache" ], "operator": "eq" }
      ],
      "metricName": "plus.cache.hit.ratio",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.checks",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.unhealthy",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${var.project_prefix}-deploy"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Inbound Flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "repeat": "vm",
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Inbound Flows - ${{__value.resourceName}}",
      "dimensionFilters": [],
      "metricName": "Inbound Flows",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${{__value.name}}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "repeat": "vm",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Disk Read - ${{__value.resourceName}}",
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${{__value.name}}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Disk Write - ${{__value.resourceName}}",
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "${var.azure_region}",
      "resources极": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${{__value.name}}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "CPU % - ${{__value.resourceName}}",
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${{__value.name}}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Available Memory - ${{__value.resourceName}}",
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "${var.azure_region}",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "${var.azure_region}",
        "resourceGroup": "${var.resource_group_name}",
        "resourceName": "${{__value.name}}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}