name: 'NGINXaaS WAF Apply'

on:
  push:
    branches: nginxaas-apply

jobs:
  terraform:
    name: 'NGINXaaS WAF'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./azure/nginxaas

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to v2
        with:
          terraform_version: 1.3.0
      
      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_storage_account_name: ${{ vars.storage_account_name }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        env:
          TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          TF_VAR_project_prefix: ${{ vars.project_prefix }}
          TF_VAR_azure_region: ${{ vars.azure_region || 'eastus2' }}
          TF_VAR_ssh_public_key: ${{ secrets.ssh_public_key }}
          TF_VAR_nginx_jwt: ${{ secrets.NGINX_JWT }}
          TF_VAR_nginx_plus_cert: ${{ secrets.nginx_plus_cert }}
          TF_VAR_nginx_plus_key: ${{ secrets.nginx_plus_key }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        env:
          TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          TF_VAR_project_prefix: ${{ vars.project_prefix }}
          TF_VAR_azure_region: ${{ vars.azure_region || 'eastus2' }}
          TF_VAR_ssh_public_key: ${{ secrets.ssh_public_key }}
          TF_VAR_nginx_jwt: ${{ secrets.NGINX_JWT }}
          TF_VAR_nginx_plus_cert: ${{ secrets.nginx_plus_cert }}
          TF_VAR_nginx_plus_key: ${{ secrets.nginx_plus_key }}

      - name: Output Deployment Results
        id: outputs
        run: |
          NGINX_ENDPOINT=$(terraform output -raw nginx_endpoint)
          VM_PUBLIC_IPS=$(terraform output -json vm_public_ips | jq -c)
          echo "NGINX_ENDPOINT=$NGINX_ENDPOINT" >> $GITHUB_OUTPUT
          echo "VM_PUBLIC_IPS=$VM_PUBLIC_IPS" >> $GITHUB_OUTPUT
          echo "NGINX Endpoint: $NGINX_ENDPOINT"
          echo "VM Public IPs: $VM_PUBLIC_IPS"